var Key = {
	"None": 0,
	"Cancel": 1,
	"Back": 2,
	"Tab": 3,
	"LineFeed": 4,
	"Clear": 5,
	"Enter": 6,
	"Pause": 7,
	"CapsLock": 8,
	"Escape": 9,
	"Space": 10,
	"PageUp": 11,
	"PageDown": 12,
	"Next": 13,
	"End": 14,
	"Home": 15,
	"Left": 16,
	"Up": 17,
	"Right": 18,
	"Down": 19,
	"Select": 20,
	"Print": 21,
	"Execute": 22,
	"PrintScreen": 23,
	"Insert": 24,
	"Delete": 25,
	"Help": 26,
	"D0": 27,
	"D1": 28,
	"D2": 29,
	"D3": 30,
	"D4": 31,
	"D5": 32,
	"D6": 33,
	"D7": 34,
	"D8": 35,
	"D9": 36,
	"A": 37,
	"B": 38,
	"C": 39,
	"D": 40,
	"E": 41,
	"F": 42,
	"G": 43,
	"H": 44,
	"I": 45,
	"J": 46,
	"K": 47,
	"L": 48,
	"M": 49,
	"N": 50,
	"O": 51,
	"P": 52,
	"Q": 53,
	"R": 54,
	"S": 55,
	"T": 56,
	"U": 57,
	"V": 58,
	"W": 59,
	"X": 60,
	"Y": 61,
	"Z": 62,
	"LWin": 63,
	"RWin": 64,
	"Apps": 65,
	"Sleep": 66,
	"NumPad0": 67,
	"NumPad1": 68,
	"NumPad2": 69,
	"NumPad3": 70,
	"NumPad4": 71,
	"NumPad5": 72,
	"NumPad6": 73,
	"NumPad7": 74,
	"NumPad8": 75,
	"NumPad9": 76,
	"Multiply": 77,
	"Add": 78,
	"Separator": 79,
	"Subtract": 80,
	"Decimal": 81,
	"Divide": 82,
	"F1": 83,
	"F2": 84,
	"F3": 85,
	"F4": 86,
	"F5": 87,
	"F6": 88,
	"F7": 89,
	"F8": 90,
	"F9": 91,
	"F10": 92,
	"F11": 93,
	"F12": 94,
	"F13": 95,
	"F14": 96,
	"F15": 97,
	"F16": 98,
	"F17": 99,
	"F18": 100,
	"F19": 101,
	"F20": 102,
	"F21": 103,
	"F22": 104,
	"F23": 105,
	"F24": 106,
	"NumLock": 107,
	"Scroll": 108,
	"LeftShift": 109,
	"RightShift": 110,
	"LeftCtrl": 111,
	"RightCtrl": 112,
	"LeftAlt": 113,
	"RightAlt": 114,
	"BrowserBack": 115,
	"BrowserForward": 116,
	"BrowserRefresh": 117,
	"BrowserStop": 118,
	"BrowserSearch": 119,
	"BrowserFavorites": 120,
	"BrowserHome": 121,
	"VolumeMute": 122,
	"VolumeDown": 123,
	"VolumeUp": 124,
	"MediaNextTrack": 125,
	"MediaPreviousTrack": 126,
	"MediaStop": 127,
	"MediaPlayPause": 128,
	"LaunchMail": 129,
	"SelectMedia": 130,
	"LaunchApplication1": 131,
	"LaunchApplication2": 132,
	"System": 133,
	"CrSel": 134,
	"ExSel": 135,
	"EraseEof": 136,
	"Play": 137,
	"Zoom": 138,
	"SemiColon": 139,
	"Comma": 140,
	"Period": 141,
	"Quote": 142,
	"BackQuote": 143,
	"Slash": 144,
	"BackSlash": 145,
	"OpenBracket": 146,
	"CloseBracket": 147,

	fromKeyCode: function (keyCode) {
		switch (keyCode) {
			case 3:
				return Key.Cancel;
			case 8:
				return Key.Back;
			case 9:
				return Key.Tab;
			case 12:
				return Key.Clear;
			case 13:
				return Key.Enter;
			case 16:
			case 160:
				return Key.LeftShift;
			case 17:
			case 162:
				return Key.LeftCtrl;
			case 18:
			case 164:
				return Key.LeftAlt;
			case 19:
				return Key.Pause;
			case 20:
				return Key.CapsLock;
			case 27:
				return Key.Escape;
			case 32:
				return Key.Space;
			case 33:
				return Key.PageUp;
			case 34:
				return Key.PageDown;
			case 35:
				return Key.End;
			case 36:
				return Key.Home;
			case 37:
				return Key.Left;
			case 38:
				return Key.Up;
			case 39:
				return Key.Right;
			case 40:
				return Key.Down;
			case 41:
				return Key.Select;
			case 42:
				return Key.Print;
			case 43:
				return Key.Execute;
			case 44:
				return Key.PrintScreen;
			case 45:
				return Key.Insert;
			case 46:
				return Key.Delete;
			case 47:
				return Key.Help;
			case 48:
				return Key.D0;
			case 49:
				return Key.D1;
			case 50:
				return Key.D2;
			case 51:
				return Key.D3;
			case 52:
				return Key.D4;
			case 53:
				return Key.D5;
			case 54:
				return Key.D6;
			case 55:
				return Key.D7;
			case 56:
				return Key.D8;
			case 57:
				return Key.D9;
			case 59:
				return Key.SemiColon;
			case 65:
				return Key.A;
			case 66:
				return Key.B;
			case 67:
				return Key.C;
			case 68:
				return Key.D;
			case 69:
				return Key.E;
			case 70:
				return Key.F;
			case 71:
				return Key.G;
			case 72:
				return Key.H;
			case 73:
				return Key.I;
			case 74:
				return Key.J;
			case 75:
				return Key.K;
			case 76:
				return Key.L;
			case 77:
				return Key.M;
			case 78:
				return Key.N;
			case 79:
				return Key.O;
			case 80:
				return Key.P;
			case 81:
				return Key.Q;
			case 82:
				return Key.R;
			case 83:
				return Key.S;
			case 84:
				return Key.T;
			case 85:
				return Key.U;
			case 86:
				return Key.V;
			case 87:
				return Key.W;
			case 88:
				return Key.X;
			case 89:
				return Key.Y;
			case 90:
				return Key.Z;
			case 91:
				return Key.LWin;
			case 92:
				return Key.RWin;
			case 93:
				return Key.Apps;
			case 95:
				return Key.Sleep;
			case 96:
				return Key.NumPad0;
			case 97:
				return Key.NumPad1;
			case 98:
				return Key.NumPad2;
			case 99:
				return Key.NumPad3;
			case 100:
				return Key.NumPad4;
			case 101:
				return Key.NumPad5;
			case 102:
				return Key.NumPad6;
			case 103:
				return Key.NumPad7;
			case 104:
				return Key.NumPad8;
			case 105:
				return Key.NumPad9;
			case 106:
				return Key.Multiply;
			case 107:
				return Key.Add;
			case 108:
				return Key.Separator;
			case 109:
				return Key.Subtract;
			case 110:
				return Key.Decimal;
			case 111:
				return Key.Divide;
			case 112:
				return Key.F1;
			case 113:
				return Key.F2;
			case 114:
				return Key.F3;
			case 115:
				return Key.F4;
			case 116:
				return Key.F5;
			case 117:
				return Key.F6;
			case 118:
				return Key.F7;
			case 119:
				return Key.F8;
			case 120:
				return Key.F9;
			case 121:
				return Key.F10;
			case 122:
				return Key.F11;
			case 123:
				return Key.F12;
			case 124:
				return Key.F13;
			case 125:
				return Key.F14;
			case 126:
				return Key.F15;
			case 127:
				return Key.F16;
			case 128:
				return Key.F17;
			case 129:
				return Key.F18;
			case 130:
				return Key.F19;
			case 131:
				return Key.F20;
			case 132:
				return Key.F21;
			case 133:
				return Key.F22;
			case 134:
				return Key.F23;
			case 135:
				return Key.F24;
			case 144:
				return Key.NumLock;
			case 145:
				return Key.Scroll;
			case 161:
				return Key.RightShift;
			case 163:
				return Key.RightCtrl;
			case 165:
				return Key.RightAlt;
			case 166:
				return Key.BrowserBack;
			case 167:
				return Key.BrowserForward;
			case 168:
				return Key.BrowserRefresh;
			case 169:
				return Key.BrowserStop;
			case 170:
				return Key.BrowserSearch;
			case 171:
				return Key.BrowserFavorites;
			case 172:
				return Key.BrowserHome;
			case 173:
				return Key.VolumeMute;
			case 174:
				return Key.VolumeDown;
			case 175:
				return Key.VolumeUp;
			case 176:
				return Key.MediaNextTrack;
			case 177:
				return Key.MediaPreviousTrack;
			case 178:
				return Key.MediaStop;
			case 179:
				return Key.MediaPlayPause;
			case 180:
				return Key.LaunchMail;
			case 181:
				return Key.SelectMedia;
			case 182:
				return Key.LaunchApplication1;
			case 183:
				return Key.LaunchApplication2;
			case 188:
				return Key.Comma;
			case 190:
				return Key.Period;
			case 191:
				return Key.Slash;
			case 192:
				return Key.BackQuote;
			case 219:
				return Key.OpenBracket;
			case 220:
				return Key.BackSlash;
			case 221:
				return Key.CloseBracket;
			case 222:
				return Key.Quote;
			case 247:
				return Key.CrSel;
			case 248:
				return Key.ExSel;
			case 249:
				return Key.EraseEof;
			case 250:
				return Key.Play;
			case 251:
				return Key.Zoom;
		}

		return Key.None;
	},

	fromCharCode: function (charCode) {
		switch (charCode) {
			case 48:
				return Key.D0;
			case 49:
				return Key.D1;
			case 50:
				return Key.D2;
			case 51:
				return Key.D3;
			case 52:
				return Key.D4;
			case 53:
				return Key.D5;
			case 54:
				return Key.D6;
			case 55:
				return Key.D7;
			case 56:
				return Key.D8;
			case 57:
				return Key.D9;
			case 59:
				return Key.SemiColon;
			case 65:
			case 97:
				return Key.A;
			case 66:
			case 98:
				return Key.B;
			case 67:
			case 99:
				return Key.C;
			case 68:
			case 100:
				return Key.D;
			case 69:
			case 101:
				return Key.E;
			case 70:
			case 102:
				return Key.F;
			case 71:
			case 103:
				return Key.G;
			case 72:
			case 104:
				return Key.H;
			case 73:
			case 105:
				return Key.I;
			case 74:
			case 106:
				return Key.J;
			case 75:
			case 107:
				return Key.K;
			case 76:
			case 108:
				return Key.L;
			case 77:
			case 109:
				return Key.M;
			case 78:
			case 110:
				return Key.N;
			case 79:
			case 111:
				return Key.O;
			case 80:
			case 112:
				return Key.P;
			case 81:
			case 113:
				return Key.Q;
			case 82:
			case 114:
				return Key.R;
			case 83:
			case 115:
				return Key.S;
			case 84:
			case 116:
				return Key.T;
			case 85:
			case 117:
				return Key.U;
			case 86:
			case 118:
				return Key.V;
			case 87:
			case 119:
				return Key.W;
			case 88:
			case 120:
				return Key.X;
			case 89:
			case 121:
				return Key.Y;
			case 90:
			case 122:
				return Key.Z;
			case 42:
				return Key.Multiply;
			case 43:
				return Key.Add;
			case 124:
				return Key.Separator;
			case 45:
				return Key.Subtract;
			case 46:
				return Key.Period;
			case 47:
				return Key.Divide;
			case 44:
				return Key.Comma;
			case 96:
				return Key.BackQuote;
			case 91:
				return Key.OpenBracket;
			case 92:
				return Key.BackSlash;
			case 93:
				return Key.CloseBracket;
			case 39:
				return Key.Quote;
		}

		return Key.None;
	},

	toKeyCode: function (key) {
		switch (key) {
			case Key.Cancel:
				return 3;
			case Key.Back:
				return 8;
			case Key.Tab:
				return 9;
			case Key.Clear:
				return 12;
			case Key.Enter:
				return 13;
			case Key.LeftShift:
				return 16;
			case Key.LeftCtrl:
				return 17;
			case Key.LeftAlt:
				return 18;
			case Key.Pause:
				return 19;
			case Key.CapsLock:
				return 20;
			case Key.Escape:
				return 27;
			case Key.Space:
				return 32;
			case Key.PageUp:
				return 33;
			case Key.PageDown:
				return 34;
			case Key.End:
				return 35;
			case Key.Home:
				return 36;
			case Key.Left:
				return 37;
			case Key.Up:
				return 38;
			case Key.Right:
				return 39;
			case Key.Down:
				return 40;
			case Key.Select:
				return 41;
			case Key.Print:
				return 42;
			case Key.Execute:
				return 43;
			case Key.PrintScreen:
				return 44;
			case Key.Insert:
				return 45;
			case Key.Delete:
				return 46;
			case Key.Help:
				return 47;
			case Key.D0:
				return 48;
			case Key.D1:
				return 49;
			case Key.D2:
				return 50;
			case Key.D3:
				return 51;
			case Key.D4:
				return 52;
			case Key.D5:
				return 53;
			case Key.D6:
				return 54;
			case Key.D7:
				return 55;
			case Key.D8:
				return 56;
			case Key.D9:
				return 57;
			case Key.SemiColon:
				return 59;
			case Key.A:
				return 65;
			case Key.B:
				return 66;
			case Key.C:
				return 67;
			case Key.D:
				return 68;
			case Key.E:
				return 69;
			case Key.F:
				return 70;
			case Key.G:
				return 71;
			case Key.H:
				return 72;
			case Key.I:
				return 73;
			case Key.J:
				return 74;
			case Key.K:
				return 75;
			case Key.L:
				return 76;
			case Key.M:
				return 77;
			case Key.N:
				return 78;
			case Key.O:
				return 79;
			case Key.P:
				return 80;
			case Key.Q:
				return 81;
			case Key.R:
				return 82;
			case Key.S:
				return 83;
			case Key.T:
				return 84;
			case Key.U:
				return 85;
			case Key.V:
				return 86;
			case Key.W:
				return 87;
			case Key.X:
				return 88;
			case Key.Y:
				return 89;
			case Key.Z:
				return 90;
			case Key.LWin:
				return 91;
			case Key.RWin:
				return 92;
			case Key.Apps:
				return 93;
			case Key.Sleep:
				return 95;
			case Key.NumPad0:
				return 96;
			case Key.NumPad1:
				return 97;
			case Key.NumPad2:
				return 98;
			case Key.NumPad3:
				return 99;
			case Key.NumPad4:
				return 100;
			case Key.NumPad5:
				return 101;
			case Key.NumPad6:
				return 102;
			case Key.NumPad7:
				return 103;
			case Key.NumPad8:
				return 104;
			case Key.NumPad9:
				return 105;
			case Key.Multiply:
				return 106;
			case Key.Add:
				return 107;
			case Key.Separator:
				return 108;
			case Key.Subtract:
				return 109;
			case Key.Decimal:
				return 110;
			case Key.Divide:
				return 111;
			case Key.F1:
				return 112;
			case Key.F2:
				return 113;
			case Key.F3:
				return 114;
			case Key.F4:
				return 115;
			case Key.F5:
				return 116;
			case Key.F6:
				return 117;
			case Key.F7:
				return 118;
			case Key.F8:
				return 119;
			case Key.F9:
				return 120;
			case Key.F10:
				return 121;
			case Key.F11:
				return 122;
			case Key.F12:
				return 123;
			case Key.F13:
				return 124;
			case Key.F14:
				return 125;
			case Key.F15:
				return 126;
			case Key.F16:
				return 127;
			case Key.F17:
				return 128;
			case Key.F18:
				return 129;
			case Key.F19:
				return 130;
			case Key.F20:
				return 131;
			case Key.F21:
				return 132;
			case Key.F22:
				return 133;
			case Key.F23:
				return 134;
			case Key.F24:
				return 135;
			case Key.NumLock:
				return 144;
			case Key.Scroll:
				return 145;
			case Key.RightShift:
				return 161;
			case Key.RightCtrl:
				return 163;
			case Key.RightAlt:
				return 165;
			case Key.BrowserBack:
				return 166;
			case Key.BrowserForward:
				return 167;
			case Key.BrowserRefresh:
				return 168;
			case Key.BrowserStop:
				return 169;
			case Key.BrowserSearch:
				return 170;
			case Key.BrowserFavorites:
				return 171;
			case Key.BrowserHome:
				return 172;
			case Key.VolumeMute:
				return 173;
			case Key.VolumeDown:
				return 174;
			case Key.VolumeUp:
				return 175;
			case Key.MediaNextTrack:
				return 176;
			case Key.MediaPreviousTrack:
				return 177;
			case Key.MediaStop:
				return 178;
			case Key.MediaPlayPause:
				return 179;
			case Key.LaunchMail:
				return 180;
			case Key.SelectMedia:
				return 181;
			case Key.LaunchApplication1:
				return 182;
			case Key.LaunchApplication2:
				return 183;
			case Key.Comma:
				return 188;
			case Key.Period:
				return 190;
			case Key.Slash:
				return 191;
			case Key.BackQuote:
				return 192;
			case Key.OpenBracket:
				return 219;
			case Key.BackSlash:
				return 220;
			case Key.CloseBracket:
				return 221;
			case Key.Quote:
				return 222;
			case Key.CrSel:
				return 247;
			case Key.ExSel:
				return 248;
			case Key.EraseEof:
				return 249;
			case Key.Play:
				return 250;
			case Key.Zoom:
				return 251;
		}

		return 0;
	}
};

export default Key;
